FROM golang:1.21.5-alpine3.19 as builder
RUN apk add --no-cache make gcc musl-dev linux-headers git jq bash wget clang
COPY ./go.mod /app/go.mod
COPY ./go.sum /app/go.sum

WORKDIR /app

RUN echo "go mod cache: $(go env GOMODCACHE)"
RUN echo "go build cache: $(go env GOCACHE)"

COPY . /app

# install mips-linux-musl-gcc
RUN wget https://musl.cc/mips-linux-musl-cross.tgz
RUN tar zxf mips-linux-musl-cross.tgz
ENV PATH=$PATH:/app/mips-linux-musl-cross/bin/
RUN echo $PATH

RUN git clone --recursive https://github.com/herumi/bls-eth-go-binary.git
RUN cd bls-eth-go-binary/src/bls && make -f Makefile.onelib ARCH=mips CLANG_TARGET=mips BIT=32 CXX=clang++ ETH_CFLAGS=-DBLS_ETH CFLAGS_USER=-DMCL_STANDALNONE
RUN cd bls-eth-go-binary/src/bls && mips-linux-musl-gcc sample/minsample.c -I include/ -I mcl/include/ bls/lib/linux/libbls384_256.a -DBLS_ETH


FROM scratch AS export-stage
COPY --from=builder /app/bls-eth-go-binary/src/bls/lib/linux/libbls384_256.a .
